name: Deploy to Coolify

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trigger Coolify Deploy
        run: |
          curl --silent --show-error --fail \
            -X GET "https://coolify.46.225.95.201.sslip.io/api/v1/deploy?uuid=dt2vqe6hsy18d2hofookbznt&force=false" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
